# Generated by Django 2.1.2 on 2019-05-13 17:16

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ContactCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='contacts.ContactCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=21)),
                ('kategori', models.CharField(choices=[('OE', 'Office Email'), ('PE', 'Personal Email'), ('OE', 'Other Email')], default='', max_length=4)),
                ('keutamaan', models.CharField(choices=[('PE', 'Primary Email'), ('SE', 'Secondary Email'), ('OE', 'Other Email')], default='', max_length=4)),
                ('remark', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombor', models.CharField(default='', max_length=21)),
                ('kategori', models.CharField(choices=[('OP', 'Office Phone'), ('PH', 'Phone'), ('HP', 'Handphone'), ('FAX', 'Fax')], default='', max_length=4)),
                ('keutamaan', models.CharField(choices=[('PN', 'Primary Number'), ('SN', 'Secondary Number'), ('ON', 'Other Number')], default='', max_length=4)),
                ('remark', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='', max_length=200)),
                ('ringkas', models.CharField(blank=True, max_length=50, null=True)),
                ('no_kp_baru', models.CharField(blank=True, default='', max_length=21, null=True)),
                ('no_kp_lama', models.CharField(blank=True, default='', max_length=21, null=True)),
                ('no_passport', models.CharField(blank=True, default='', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warganegara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='', max_length=200)),
                ('ringkas', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('int_code', models.CharField(blank=True, default='', max_length=4, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mycontacts',
            name='warganegara',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Warganegara'),
        ),
        migrations.AddField(
            model_name='contactphone',
            name='empunya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.MyContacts'),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='empunya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.MyContacts'),
        ),
    ]
