# Generated by Django 2.1.2 on 2019-05-14 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactaddress',
            options={'verbose_name_plural': 'Address'},
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='alamat1',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='alamat2',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='alamat3',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='alamat4',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='bandar',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='bandar2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='empunya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.MyContacts'),
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='kategori',
            field=models.CharField(choices=[('OA', 'Office Address'), ('HA', 'Personal Address'), ('OT', 'Other Address')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='keutamaan',
            field=models.CharField(choices=[('PE', 'Primary Address'), ('SE', 'Secondary Address'), ('OE', 'Other Address')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='negara',
            field=models.CharField(blank=True, default='', help_text='for other than Malaysia only', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='negeri',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='poskod',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
