# Generated by Django 2.1.2 on 2019-05-26 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20190514_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactaddress',
            name='alamat3',
            field=models.CharField(blank=True, default='', help_text='optional', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactaddress',
            name='alamat4',
            field=models.CharField(blank=True, default='', help_text='optional', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactaddress',
            name='bandar2',
            field=models.CharField(blank=True, default='', help_text='optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactaddress',
            name='kategori',
            field=models.CharField(choices=[('OA', 'Office Address'), ('HA', 'Home Address'), ('OT', 'Other Address')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='contactemail',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='empunya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.MyContacts', verbose_name='Owner'),
        ),
    ]
