# Generated by Django 2.1.2 on 2019-02-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rujukan', models.CharField(default='', max_length=70)),
                ('nama', models.CharField(default='', max_length=120)),
                ('kategori', models.CharField(choices=[('CO', 'CONVEYANCING'), ('LI', 'LITIGATION'), ('SY', 'SYARIAH'), ('OT', 'OTHERS')], default='', max_length=2)),
                ('kat_pelanggan', models.CharField(choices=[('IND', 'INDIVIDU'), ('SYA', 'SYARIKAT'), ('AGE', 'AGENSI'), ('NGO', 'NGO'), ('LL', 'LAIN-LAIN')], default='', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Client Folder',
            },
        ),
    ]
