# Generated by Django 2.1.2 on 2019-02-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfolder',
            name='kat_pelanggan',
            field=models.CharField(choices=[('IN', 'INDIVIDU'), ('SY', 'SYARIKAT'), ('AG', 'AGENSI'), ('NG', 'NGO'), ('LL', 'LAIN-LAIN')], default='', max_length=2),
        ),
    ]
