# Generated by Django 2.1.2 on 2019-03-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0002_auto_20190226_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfolder',
            name='kat_pelanggan',
            field=models.CharField(choices=[('IND', 'INDIVIDU'), ('SYA', 'SYARIKAT'), ('AGE', 'AGENSI'), ('NGO', 'NGO'), ('LLA', 'LAIN-LAIN')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='clientfolder',
            name='kategori',
            field=models.CharField(choices=[('CO', 'CONVEYANCING'), ('LI', 'LITIGATION'), ('SY', 'SYARIAH'), ('OT', 'OTHERS')], default='', max_length=3),
        ),
    ]
