# Generated by Django 2.1.2 on 2019-03-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0003_auto_20190321_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfolder',
            name='keutamaan',
            field=models.CharField(choices=[('1', 'PALING PENTING'), ('2', 'SANGAT PENTING'), ('3', 'PENTING'), ('4', 'BIASA'), ('5', 'KURANG PENTING'), ('6', 'TIDAK PENTING'), ('7', 'BOLEH ABAI')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='clientfolder',
            name='status_folder',
            field=models.CharField(choices=[('AK', 'Aktif'), ('TA', 'Tidak Aktif'), ('DP', 'Dalam Proses'), ('TG', 'Tangguh'), ('BT', 'Batal'), ('SE', 'Selesai')], default='', max_length=2),
        ),
    ]
