# Generated by Django 2.1.2 on 2019-05-08 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0005_auto_20190321_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientfolder',
            name='kategori',
        ),
    ]
