# Generated by Django 2.1.2 on 2019-05-08 03:59

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('folder', '0006_remove_clientfolder_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfolder',
            name='kategori',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Kategori'),
        ),
    ]
