# Generated by Django 2.1.2 on 2019-05-13 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190513_2309'),
        ('folder', '0007_clientfolder_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfolder',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Partners'),
        ),
        migrations.AddField(
            model_name='clientfolder',
            name='solicitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Solicitors'),
        ),
        migrations.AddField(
            model_name='clientfolder',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Staff'),
        ),
    ]
