# Generated by Django 2.1.2 on 2019-05-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0008_auto_20190513_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfolder',
            name='closing_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='clientfolder',
            name='opening_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
