# Generated by Django 2.1.2 on 2019-05-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0009_auto_20190513_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfolder',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientfolder',
            name='opening_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
