# Generated by Django 2.1.2 on 2019-05-27 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20190526_1827'),
        ('folder', '0010_auto_20190514_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfolder',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.MyContacts'),
        ),
    ]
