# Generated by Django 2.1.2 on 2019-08-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0011_clientfolder_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfolder',
            name='image',
            field=models.ImageField(default='default2.jpg', upload_to='folder_img'),
        ),
    ]
