# Generated by Django 3.0.3 on 2020-02-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0012_clientfolder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfolder',
            name='image',
            field=models.ImageField(default='folder_img/default2.jpg', upload_to='folder_img'),
        ),
    ]
