# Generated by Django 2.1.2 on 2019-02-26 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folder', '0002_auto_20190226_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conveyancing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hartanah', models.CharField(default='', max_length=250)),
                ('ringkas', models.CharField(default='', max_length=100)),
                ('penjual', models.CharField(default='', max_length=250)),
                ('pembeli', models.CharField(default='', max_length=250)),
                ('pemaju', models.CharField(default='', max_length=250)),
                ('pemilik', models.CharField(default='', max_length=250)),
                ('rujukan', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='folder.ClientFolder')),
            ],
            options={
                'verbose_name_plural': 'Conveyancing',
            },
        ),
    ]
