# Generated by Django 2.1.2 on 2019-02-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveyancing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conveyancing',
            name='hartanah',
            field=models.TextField(default=''),
        ),
    ]
