# Generated by Django 2.1.2 on 2019-03-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveyancing', '0002_auto_20190226_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisHartanah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('KED', 'KEDIAMAN'), ('PEJ', 'PEJABAT'), ('TAN', 'TANAH')], default='', max_length=3)),
                ('nama', models.CharField(default='', max_length=250)),
                ('aktif', models.CharField(choices=[('A', 'Aktif'), ('T', 'Tidak Aktif')], default='A', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Jenis Hartanah',
                'ordering': ('kategori', 'nama'),
            },
        ),
    ]
