# Generated by Django 2.1.2 on 2019-03-21 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conveyancing', '0003_jenishartanah'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveyancing',
            name='hartanahMalay',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='conveyancing',
            name='jenisConveyancing',
            field=models.CharField(choices=[('BELIAN', 'BELIAN'), ('JUALAN', 'JUALAN'), ('PINDAH MILIK', 'PINDAH MILIK'), ('PUSAKA', 'PUSAKA')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='conveyancing',
            name='jenisHartanah',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='conveyancing.JenisHartanah'),
            preserve_default=False,
        ),
    ]
