# Generated by Django 2.1.2 on 2019-05-13 07:23

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0007_clientfolder_kategori'),
        ('tugasan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoritugasan',
            options={'verbose_name_plural': 'Kategori Tugasan'},
        ),
        migrations.AddField(
            model_name='mytugasan',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='folder.ClientFolder'),
        ),
        migrations.AddField(
            model_name='mytugasan',
            name='kategori_tugasan',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tugasan.KategoriTugasan'),
        ),
        migrations.AddField(
            model_name='mytugasan',
            name='nama',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='mytugasan',
            name='status_tugasan',
            field=models.CharField(choices=[('FN', 'FINISHED'), ('PD', 'PENDING'), ('OP', 'ON PROGRESS'), ('CA', 'CANCEL'), ('HT', 'HALTED'), ('NA', 'NOT APLICABLE')], default='', max_length=2),
        ),
    ]
