# Generated by Django 2.1.2 on 2019-05-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugasan', '0002_auto_20190513_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytugasan',
            name='status_tugasan',
            field=models.CharField(choices=[('FN', 'FINISHED'), ('PD', 'PENDING'), ('OP', 'ON PROGRESS'), ('CA', 'CANCEL'), ('HT', 'HALTED'), ('NA', 'NOT APLICABLE'), ('ST', 'STARTED')], default='ST', max_length=2),
        ),
    ]
