# Generated by Django 2.1.2 on 2018-12-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='subdomain_prefix',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
