# Generated by Django 2.1.2 on 2019-05-08 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cawangan'),
        ('akaun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='akaunbank',
            name='bank',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='akaunbank',
            name='cawangan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Cawangan'),
        ),
        migrations.AddField(
            model_name='akaunbank',
            name='cawangan_bank',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='akaunbank',
            name='jenis',
            field=models.CharField(choices=[('CLIENT', 'CLIENT ACCOUNT'), ('OFFICE', 'OFFICE ACCOUNT'), ('OTHER', 'OTHER ACCOUNT')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='akaunbank',
            name='no_akaun',
            field=models.CharField(default='', max_length=20),
        ),
    ]
