# Generated by Django 2.1.2 on 2019-05-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akaun', '0003_auto_20190508_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoritransaksi',
            options={'verbose_name_plural': 'Kategori Transaksi'},
        ),
    ]
