# Generated by Django 2.1.2 on 2019-07-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akaun', '0004_auto_20190513_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('level1', 'Level 1 Permission'), ('level2', 'Level 2 Permission'), ('level3', 'Level 3 Permission'), ('level4', 'Level 4 Permission'), ('level5', 'Level 5 Permission'), ('level6', 'Level 6 Permission'), ('level7', 'Level 7 Permission')),
                'managed': False,
            },
        ),
    ]
