# Generated by Django 2.1.2 on 2019-05-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cawangan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, unique=True)),
                ('ringkas', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
