# Generated by Django 2.1.2 on 2019-05-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_partners_solicitors_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='initial',
            field=models.CharField(blank=True, default='', max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='solicitors',
            name='initial',
            field=models.CharField(blank=True, default='', max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='initial',
            field=models.CharField(blank=True, default='', max_length=21, null=True),
        ),
    ]
