# Generated by Django 2.1.2 on 2019-05-28 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folder', '0011_clientfolder_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceParticular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bil_no', models.CharField(default='Proforma Invoice', max_length=100)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('part1', models.TextField()),
                ('part2', models.TextField()),
                ('part3', models.TextField()),
                ('part4', models.TextField()),
                ('part5', models.TextField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=11)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder.ClientFolder')),
            ],
        ),
    ]
