# Generated by Django 2.1.2 on 2019-05-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceparticular',
            name='taxed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceparticular',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
